name: Deploy Node Microservices to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2.pem
          chmod 400 ~/.ssh/ec2.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy code to EC2
        run: |
          rsync -avz \
            --exclude node_modules \
            --exclude .git \
            -e "ssh -i ~/.ssh/ec2.pem" \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app

      - name: Install dependencies & reload services
        run: |
          ssh -i ~/.ssh/ec2.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app/user-service && npm install
            cd ~/app/order-service && npm install
            cd ~/app/payment-service && npm install
            pm2 reload all
          EOF
